name: kprn
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  badges: ^2.0.3
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  ethers: ^0.0.1+3
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  http: ^0.13.4
  intl: ^0.17.0
  page_transition: ^2.0.7
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  walletconnect_dart: ^0.0.11
  web3dart: ^2.3.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter
  shared_preferences_ios: ^2.1.1

flutter_native_splash:
  image: assets/images/logo.png
  color: "#151925"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-small.png"
  adaptive_icon_background: "#151925"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/abis/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/inter/Inter-Black.ttf
          weight: 900
